import { Injectable } from "@angular/core";

@Injectable(
    {providedIn:'root'}
)
export class UserService{

    countries!:string[];
    cities!:string[];

    getCountries(): string[]{
        this.countries = [
            "Afghanistan",
            "Albania",
            "Algeria",
            "Andorra",
            "Angola",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bhutan",
            "Bolivia",
            "Bosnia and Herzegovina",
            "Botswana",
            "Brazil",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cabo Verde",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Colombia",
            "Comoros",
            "Congo, Democratic Republic of the",
            "Congo, Republic of the",
            "Costa Rica",
            "Cote d'Ivoire",
            "Croatia",
            "Cuba",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Eswatini",
            "Ethiopia",
            "Fiji",
            "Finland",
            "France",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Greece",
            "Grenada",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq"]
            return this.countries;
    }

    getCities():string[]{
        this.cities = [
            "Amsterdam",
            "Barcelona",
            "Berlin",
            "Chicago",
            "Dubai",
            "Edinburgh",
            "Florence",
            "Geneva",
            "Helsinki",
            "Istanbul",
            "Jakarta",
            "Kuala Lumpur",
            "London",
            "Madrid",
            "New York",
            "Oslo",
            "Paris",
            "Quebec City",
            "Rome",
            "Stockholm",
            "Toronto",
            "Vancouver",
            "Washington D.C."]

            return this.cities;
    }

}